// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvnOQC2GjLOiCmgeD8OuAZwVnBEruA18I',
    appId: '1:677054697948:web:c90caeb32e67821a6dff19',
    messagingSenderId: '677054697948',
    projectId: 'togetherdo-c9179',
    authDomain: 'togetherdo-c9179.firebaseapp.com',
    storageBucket: 'togetherdo-c9179.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO_H1SuQ5e9nwg9RbuI_TuysZoV_PKWjw',
    appId: '1:677054697948:android:cafcf10cff8575d06dff19',
    messagingSenderId: '677054697948',
    projectId: 'togetherdo-c9179',
    storageBucket: 'togetherdo-c9179.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU7ldL2agKApKF4LjOtf3bcfZBn3DOeeQ',
    appId: '1:677054697948:ios:a83e32a5ee5a108f6dff19',
    messagingSenderId: '677054697948',
    projectId: 'togetherdo-c9179',
    storageBucket: 'togetherdo-c9179.firebasestorage.app',
    iosBundleId: 'com.example.togetherdo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU7ldL2agKApKF4LjOtf3bcfZBn3DOeeQ',
    appId: '1:677054697948:ios:a83e32a5ee5a108f6dff19',
    messagingSenderId: '677054697948',
    projectId: 'togetherdo-c9179',
    storageBucket: 'togetherdo-c9179.firebasestorage.app',
    iosBundleId: 'com.example.togetherdo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvnOQC2GjLOiCmgeD8OuAZwVnBEruA18I',
    appId: '1:677054697948:web:382a6b4c9cf88b236dff19',
    messagingSenderId: '677054697948',
    projectId: 'togetherdo-c9179',
    authDomain: 'togetherdo-c9179.firebaseapp.com',
    storageBucket: 'togetherdo-c9179.firebasestorage.app',
  );

}